apiVersion: v1
kind: Service
metadata:
  name: statsd
spec:
  selector:
    app: statsd-daemon
  clusterIP: None
  ports:
  - port: 8125
    name: incoming-udp
    protocol: UDP
  - port: 8126
    name: admin
    protocol: TCP

